version: '3.8'

services:
  backend:
    image: your-dockerhub-username/word-to-pdf-backend:latest
    container_name: word-to-pdf-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    restart: unless-stopped

  frontend:
    image: your-dockerhub-username/word-to-pdf-frontend:latest
    container_name: word-to-pdf-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
